dictonary = {"round_pocket": [["Введите диаметр отверстия: ", "telegram_bot/graphic_explan/round_pocket/diamert_otw.jpg"], 
                              ["Введите глубину отверстия, пишется с отрицательным значением: ", "telegram_bot/graphic_explan/round_pocket/glubina_otw.jpg"], 
                              ["Введите шаг фрезерования по Z: ", "telegram_bot/graphic_explan/round_pocket/shag_frezerow.jpg"], 
                              ["Введите поверхность детали: ", "telegram_bot/graphic_explan/round_pocket/power_detali.jpg"], 
                              ["Введите радиус фрезы: ", "telegram_bot/graphic_explan/round_pocket/radius_frezj.jpg"], 
                              ["Коэффициент перекрытия фрезы, 1-полный радиус: ", "telegram_bot/graphic_explan/round_pocket/perek_frezj.jpg"], 
                              ["Введите безопасное растояние подъезда", "telegram_bot/graphic_explan/round_pocket/bezop_pod.jpg"], 
                              ["Введите безопасное растояние отъезда", "telegram_bot/graphic_explan/round_pocket/bezop_ot.jpg"]],
            "rectangular_pocket": [["Введите длину кармана: ", "telegram_bot/graphic_explan/rectangular_pocket/dlina_karmana.jpg"], 
                                   ["Введите ширину кармана: ", "telegram_bot/graphic_explan/rectangular_pocket/shirina_karmana.jpg"],
                                   ["Введите радиус в углу: ", "telegram_bot/graphic_explan/rectangular_pocket/radius_ugla.jpg"],
                                   ["Введите радиус фрезы: ", "telegram_bot/graphic_explan/rectangular_pocket/radius_frezj.jpg"],
                                   ["Поверхность детали: ", "telegram_bot/graphic_explan/rectangular_pocket/powerh_detali.jpg"], 
                                   ["Введите глубину кармана, пишется с отрицательным значением: ", "telegram_bot/graphic_explan/rectangular_pocket/glubina_karmana.jpg"],
                                   ["Введите безопасное расстояние подъезда: ", "telegram_bot/graphic_explan/rectangular_pocket/bezop_pod.jpg"],
                                   ["Введите расстояние отъезда: ", "telegram_bot/graphic_explan/rectangular_pocket/bezop_ot.jpg"],  
                                   ["Введите шаг фрезерования: ", "telegram_bot/graphic_explan/rectangular_pocket/shag_frezer.jpg"], 
                                   ["Коэффициент перекрытия фрезы, 1 = радиус фрезы: ", "telegram_bot/graphic_explan/rectangular_pocket/koef_perekr.jpg"]],
            "radius_pocket": [["Введите ширину кармана: ", "telegram_bot/graphic_explan/radius_pocket/shirina_karmana.jpg"], 
                              ["Введите длину кармана в градусах: ", "telegram_bot/graphic_explan/radius_pocket/dlina_karmana.jpg"], 
                              ["Введите глубину кармана, пишется с отрицательным значением: ", "telegram_bot/graphic_explan/radius_pocket/glubina.jpg"], 
                              ["Поверхность детали: ", "telegram_bot/graphic_explan/radius_pocket/powerh_detali.jpg"], 
                              ["Начальный угол: ", "telegram_bot/graphic_explan/radius_pocket/nachal_ugol.jpg"], 
                              ["Средний радиус паза: ", "telegram_bot/graphic_explan/radius_pocket/srednij_radius.jpg"], 
                              ["Введите радиус фрезы: ", "telegram_bot/graphic_explan/radius_pocket/radius_frez.jpg"], 
                              ["Введите шаг фрезерования: ", "telegram_bot/graphic_explan/radius_pocket/shag_frezer.jpg"], 
                              ["Коэффициент перекрытия фрезы: ", "telegram_bot/graphic_explan/radius_pocket/koef_perek.jpg"]],
            "milling _plane": [["Введите радиус фрезы", "telegram_bot/graphic_explan/milling _plane/radius_frezj.jpg"],
                               ["Введите длину плоскости", "telegram_bot/graphic_explan/milling _plane/dlina_ploskosti.jpg"],
                               ["Введите высоту плоскости", "telegram_bot/graphic_explan/milling _plane/wisota_ploskosti.jpg"],
                               ["Введите поверхность детали", "telegram_bot/graphic_explan/milling _plane/nach_Z.jpg"],
                               ["Введите конечную глубину фрезерования, задается с отрицательным значением", "telegram_bot/graphic_explan/milling _plane/konech_Z.jpg"],
                               ["Введите левый край X", "telegram_bot/graphic_explan/milling _plane/nach_X.jpg"],
                               ["Введите нижний край Y", "telegram_bot/graphic_explan/milling _plane/nach_Y.jpg"],
                               ["Введите шаг фрезерования", "telegram_bot/graphic_explan/milling _plane/shag_frez.jpg"],
                               ["Введите коэффициент перекрытия", "telegram_bot/graphic_explan/milling _plane/koef_radius.jpg"],
                               ["Введите безопасный подъезд по X", "telegram_bot/graphic_explan/milling _plane/bezop_X.jpg"],
                               ["Введите расстояние отскока перебега фрезы", "telegram_bot/graphic_explan/milling _plane/rast_otskoka.jpg"],
                               ["Введите безопасный отъезд", "telegram_bot/graphic_explan/milling _plane/2-bezopas_rast.jpg"]],
            "conical_thread": [["Введите диаметр резьбы в мм", "telegram_bot/graphic_explan/conical_thread/diametr rez.jpg"],
                               ["Введите радиус фрезы или резца", "telegram_bot/graphic_explan/conical_thread/radius_frez.jpg"],
                               ["Введите поверхность детали", "telegram_bot/graphic_explan/conical_thread/power_det.jpg"],
                               ["Введите угол с которого начинается виток", "telegram_bot/graphic_explan/conical_thread/nach_ugol.jpg"],
                               ["Введите угол конической резьбы на сторону", "telegram_bot/graphic_explan/conical_thread/ugol_konusa.jpg"],
                               ["Введите шаг резьбы", "telegram_bot/graphic_explan/conical_thread/shag_rezbji.jpg"],
                               ["Введите безопасное расстояние подъезда", "telegram_bot/graphic_explan/conical_thread/bez_rast.jpg"],
                               ["Введите безопасный отъезд", "telegram_bot/graphic_explan/conical_thread/bezop_otezd.jpg"],
                               ["Введите глубину резьбы, задается с отрицательным значением", "telegram_bot/graphic_explan/conical_thread/glubina_rezbji.jpg"],
                               ["Введите длину отрезка, хорду", "telegram_bot/graphic_explan/conical_thread/razmer_hordji.jpg"]],
            "cutting_mode": ["Введите скорость Vc", "Введите диаметр фрезы D", "Введите число зубев Z", "Введите съем на зуб Fz"],
            "degrees_decimal": ['Введите градусы (целое число): ', 'Введите минуты (целое число):', 'Введите секунды (целое число):', 'Введите радиус:'],
            "part_price": {'Круг':[["Введите марку сплава", "telegram_bot/graphic_explan/dimensions_workpiece/poyasnenie.jpg"], 
                                   ["Введите диаметр в мм", "telegram_bot/graphic_explan/dimensions_workpiece/Дииаметра прутка.jpg"], 
                                   ["Длину в мм", "telegram_bot/graphic_explan/dimensions_workpiece/длина прутка.jpg"]],
                            'Квадрат': [["Введите марку сплава", "telegram_bot/graphic_explan/dimensions_workpiece/poyasnenie.jpg"], 
                                        ["Введите сторону квадрата в мм", "telegram_bot/graphic_explan/dimensions_workpiece/сторона квадрата.jpg"], 
                                        ["Длину в мм", "telegram_bot/graphic_explan/dimensions_workpiece/длина квадрата.jpg"]],
                            'Труба': [["Введите марку сплава", "telegram_bot/graphic_explan/dimensions_workpiece/poyasnenie.jpg"], 
                                      ["Введите диаметр трубы в мм", "telegram_bot/graphic_explan/dimensions_workpiece/Диаметр трубы.jpg"], 
                                      ["Длину в мм", "telegram_bot/graphic_explan/dimensions_workpiece/длина трубы.jpg"], 
                                      ["Введите толщину стенки в мм", "telegram_bot/graphic_explan/dimensions_workpiece/толщина стенки трубы.jpg"]],
                            'Лист': [["Введите марку сплава", "telegram_bot/graphic_explan/dimensions_workpiece/poyasnenie.jpg"], 
                                     ["Введите ширину листа", "telegram_bot/graphic_explan/dimensions_workpiece/ширина листа.jpg"], 
                                     ["Длину листа", "telegram_bot/graphic_explan/dimensions_workpiece/длина листа.jpg"], 
                                     ["Введите толщину листа в мм", "telegram_bot/graphic_explan/dimensions_workpiece/толщина листа.jpg"]],
                            'Шестигранник': [["Введите марку сплава", "telegram_bot/graphic_explan/dimensions_workpiece/poyasnenie.jpg"], 
                                             ["Введите размер в мм", "telegram_bot/graphic_explan/dimensions_workpiece/размер шестигранника.jpg"], 
                                             ["Длину в мм", "telegram_bot/graphic_explan/dimensions_workpiece/длина шестигранника.jpg"]]},
                            "UFG":["Введите угол вокруг оси X: ", "Введите угол вокруг оси Z: "]
            } 

